#declare storage txd:storage

# reset everything generated by txd
data remove storage txd:storage root
scoreboard objectives remove txd_global
scoreboard objectives remove txd_used_wfoas

# (re)create scoreboards
scoreboard objectives add txd_global dummy
scoreboard objectives add txd_used_wfoas used:warped_fungus_on_a_stick

#declare score_holder $1000
scoreboard players set $1000 txd_global 1000

# make helper box near world border
forceload add 42069 29999999
fill 42079 304 29999984 42064 319 29999999 minecraft:sea_lantern hollow
setblock 42077 305 29999986 minecraft:oak_sign

tellraw @a {"text": "TXD Loaded!", "color": "gold"}